name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install libpam0g-dev pamtester
    - name: build
      run: cd src/ && make
    - name: run tests
      run: |-
        cd tests/
        hostname -f > .tests_permitted
        sudo ./test-pam_mpa.sh
